[project]
name = "userland"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "importchecker>=3.0",
    "pyroute2>=0.9.2",
]
